# Generated by Django 4.0.4 on 2022-05-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_table_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Таблица', 'verbose_name_plural': 'Таблицы'},
        ),
        migrations.AlterField(
            model_name='table',
            name='costRUB',
            field=models.IntegerField(default=0, verbose_name='Стоимость ₽'),
        ),
    ]
