# Generated by Django 4.0.4 on 2022-05-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_table_options_alter_table_costrub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='costRUB',
            field=models.FloatField(default=0, verbose_name='Стоимость ₽'),
        ),
    ]
