# Generated by Django 4.0.4 on 2022-05-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_table_costrub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='date',
            field=models.CharField(max_length=30, verbose_name='Срок поставки'),
        ),
    ]
