# Generated by Django 4.0.4 on 2022-05-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order',
            new_name='orderN',
        ),
    ]
