# Generated by Django 4.0.4 on 2022-05-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_order_orders_ordern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='orderN',
            new_name='ordernumber',
        ),
    ]
