# Generated by Django 4.0.4 on 2022-05-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_ordern_orders_ordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
