# Generated by Django 4.0.4 on 2022-05-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_orders_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
    ]
