# Generated by Django 4.0.4 on 2022-05-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('ordernumber', models.IntegerField(verbose_name='Заказ №')),
            ],
        ),
    ]
